### ISSUE TITLE
[BUG] Using precision tests with unsupported types triggers undefined behavior 

### ISSUE THREAD

**Issue by mjacobse** [jfalcou/tts#76]
**Describe the bug**
Passing non-integral, non-float types into the precision tests `TTS_ABSOLUTE_EQUAL`, `TTS_RELATIVE_EQUAL` or `TTS_ULP_EQUAL`/`TTS_IEEE_EQUAL`  will cause execution to reach the end of a value-returning function without returning a value in `absolute_distance`, `relative_distance` or `ulp_distance` respectively.

**To Reproduce**
```c++
TTS_CASE("Test")
{
    TTS_ABSOLUTE_EQUAL("a", "b", 0);
};
```
(see https://godbolt.org/z/3sc5xK4Ko). Or, more likely to happen accidentally in practice:
```c++
TTS_CASE("Test")
{
    TTS_ABSOLUTE_EQUAL(std::vector{3}, std::vector{5}, 0);  // oops, meant to use TTS_ALL_ABSOLUTE_EQUAL
};
```

**Expected behavior**
I understand of course that this is an error on the user's side and something they have to fix. However, I expected a compilation error (or if not that, at least just a failed test) for such wrong inputs. I think adding a `static_assert` (something along the likes of https://godbolt.org/z/K886v48bT) or perhaps a concept for the input type of the functions would make this a lot more user-friendly.

**Desktop (please complete the following information):**
 - OS: any
 - Compiler: any
 - Version: trunk, v2.2, v2.1, v2.0, v1.0, v0.2, v0.1

**Comment by jfalcou** [comment]
The absolument and relative should work with all types so this is indeed a bug.
The static assert on ULP related tests is also a good point.

**Comment by jfalcou** [comment]
OK added a message akin to 

```c++
        static_assert ( std::is_floating_point_v<T> || std::is_integral_v<T>
                      , "[TTS] TTS_ABSOLUTE_EQUAL requires integral or floating points data to compare."
                        "Did you mean to use TTS_ALL_ABSOLUTE_EQUAL or to overload tts::absolute_distance ?"
                      );
```

to all such functions. PR will be run and merged on cycling

**Comment by jfalcou** [comment]
and merged
