### ISSUE TITLE
[Feature] TTS_FAIL to support <<

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [jfalcou/tts#86]
At the moment it seems like it doesn't

**Comment by DenisYaroshevskiy** [comment]
Same for TTS_EXPECT_COMPILES if I didn't mess that up

**Comment by jfalcou** [comment]
```
int x = 42;
TTS_FAIL("This is " << x << "!");
```

works as all info macro consume << chains.
There is no external logger though as no test are taking place.
